# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        rectangle:
            filters:
                fixed:
                    # set the fixed size to "120x90" pixels
                    width: 800
                    height: 600
                background: { size: [ 804, 04 ], position: center, color: '#000000' }
