vich_uploader:
    db_driver: orm

    mappings:
        upload_images:
            uri_prefix: /uploads/image
            upload_destination: '%kernel.project_dir%/public/uploads/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer